name: simaskuli
description: "A new Flutter project."
publish_to: "none"
version: 0.1.2

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.1
  http: ^1.2.1
  intl: ^0.19.0
  latlong2: ^0.9.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
